config/routes.rb
Raganow::Application.routes.draw do
  resources :ragas, only: %i(index show) do
    collection do
      get :suggestion
    end
  end
  resources :clips, only: :create
  resources :pages, only: :show

  root controller: "ragas", action: "index"
end

app/models/clip.rb
class Clip
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :raga, touch: true, index: true, counter_cache: true

  field :title, type: String
  field :url, type: String
  field :embed_code, type: String
  field :thumbnail_url, type: String

  validates_presence_of :raga
  validates_presence_of :url
  validates_presence_of :title, if: :url
  validates_uniqueness_of :url, scope: :raga_id
  validate :validate_info, if: lambda { url.present? }

  before_validation :set_attributes_from_info, if: :info

  def info
    @video_info ||= VideoInfo.get(url)
  rescue VideoInfo::UrlError => e
    if e.message.downcase.include? "url is not usable"
      nil
    else
      raise
    end
  end

  private
  def validate_info
    errors.add(:url, :invalid) unless info
  end

  def set_attributes_from_info
    self.title = info.title unless self.title.present?
    self.thumbnail_url = info.thumbnail_medium
    self.embed_code = info.embed_code(iframe_attributes: { width: 425, height: 344 })
  end
end

app/models/raga.rb
class Raga
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :clips
  field :clips_count, type: Integer, default: 0

  field :title, type: String
  field :description, type: String
  field :ascending_scale, type: String
  field :descending_scale, type: String
  field :pakad, type: String
  field :drone, type: String
  field :time, type: String
  field :chakra, type: String
  field :spotify_playlist_url, type: String
  field :url, type: String
  field :thaat, type: String
  field :vaadi, type: String
  field :samvaadi, type: String

  validates_presence_of :title
  validates_presence_of :ascending_scale
  validates_presence_of :descending_scale

  validates_uniqueness_of :title, :case_sensitive => false

  acts_as_url :title, :sync_url => true

  def self.playable
    self.or({:spotify_playlist_url.ne => nil}, {:clips_count.gt => 0})
  end

  def to_s
    title
  end

  def to_param
    url
  end

  def pretty_time
    Raga.time_options.invert[time]
  end

  def pretty_chakra
    Raga.chakra_options.invert[chakra]
  end

  # Strip beginning of "Rag Puriya Kalyan: spotify:user:duztdruid:playlist:11Nsl0P9qDqbvDTwu5WB5d")
  def spotify_playlist_url=(url)
    if url.present?
      url = url["spotify:"] ? url[url.rindex("spotify:")..-1] : url #
      write_attribute(:spotify_playlist_url, url)
    end
  end

  def self.time_options
    ActiveSupport::OrderedHash[
      "06-09", "1",
      "09-12", "2",
      "12-15", "3",
      "15-18", "4",
      "18-21", "5",
      "21-24", "6",
      "24-03", "7",
      "03-06", "8",
      "Monsoon", "m"
    ]
  end

  def self.chakra_options
    ActiveSupport::OrderedHash[
      "Left Mooladhara", "left_mooladhara",
      "Mooladhara", "mooladhara",
      "Right Mooladhara", "right_mooladhara",
      "Left Swadisthan", "left_swadisthan",
      "Swadisthan", "swadisthan",
      "Right Swadisthan", "right_swadisthan",
      "Left Nabhi", "left_nabhi",
      "Nabhi", "nabhi",
      "Right Nabhi", "right_nabhi",
      "Void", "void",
      "Left Heart", "left_heart",
      "Heart", "heart",
      "Right Heart", "right_heart",
      "Left Vishuddhi", "left_vishuddhi",
      "Vishuddhi", "vishuddhi",
      "Right Vishuddhi", "right_vishuddhi",
      "Left Agnya", "left_agnya",
      "Agnya", "agnya",
      "Right Agnya", "right_agnya",
      "Left Sahastrara", "left_sahasrara",
      "Sahastrara", "sahasrara",
      "Right Sahastrara", "right_sahasrara"
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  def create
    clip_params = params.require(:clip).permit(:url, :raga_id)

    @clip = Clip.new(clip_params)
    @raga = @clip.raga

    if @clip.save
      expire_fragment "all_ragas"
      redirect_to @raga, notice: "The clip was successfully added"
    else
      flash.now[:error] = "Failed to add clip. Please make sure it's a valid YouTube URL"
      render "ragas/show"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render "#{params[:id]}"
  end
end

app/controllers/ragas_controller.rb
class RagasController < ApplicationController
  def index
    @order = params[:order] || "title"
  end

  def show
    @raga = Raga.find_by!(slug: params[:id])
    @clip = Clip.new(raga: @raga)
  end

  def suggestion
    session[:time_zone_offset] = params[:time_zone_offset].to_i.hours

    render partial: "suggestion"
  end

  private

  def ragas
    @ragas ||= Raga.where(params[:filter]&.permit! || {}).order(@order => "ASC")
  end
  helper_method :ragas
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title)
    @page_title = title
  end

  def attribute_for(object, attribute, options = {})
    value = options[:value] || object.send(attribute)
    "<p><strong>#{object.class.human_attribute_name(attribute)}</strong><br> #{value}</p>".html_safe
  end

  def chakra_image(chakra)
    chakra = chakra.split("_").last
    image_tag "chakra_#{chakra}.jpg", alt: "", class: "chakra-image"
  end

  def pretty_clock
    local_time.strftime("%H:%M")
  end

  def raga_suggestion
    raga_suggestion = Raga.playable.where(time: time_to_prahar).sample
    "Why not try raga #{link_to(raga_suggestion, raga_suggestion)}.".html_safe
  end

  def local_time
    Time.now.utc + session[:time_zone_offset]
  end

  def time_to_prahar
    prahar_and_hours.each do |prahar, time_range|
      return prahar if time_range.include?(local_time.hour)
    end
  end

  private
  def prahar_and_hours
    ActiveSupport::OrderedHash[
      1, 6..8,
      2, 9..11,
      3, 12..14,
      4, 15..17,
      5, 18..20,
      6, 21..23,
      7, [23, 0, 1, 2],
      8, 3..5
    ]
  end
end

app/views/layouts/_flash_messages.html.haml
-[:notice, :error].each do |message|
  %div.flash_message{:id => message, :style => "display: #{flash[message].blank? ? 'none' : 'block'}"}
    = h(flash[message]) if flash[message]

app/views/layouts/_menu.html.haml
%ul
  %li.first= link_to "Home", root_path
  %li= link_to "Ragas", ragas_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @page_title %> - Raagtime</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <%- if params[:action] == "index" %>
      <meta name="description" content="Raagtime is a database of Indian ragas (classical music) including spotify links for listening and recommendation of what time of day they should be listened to.">
    <% end %>
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40500274-1', 'auto');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    <div class="container">
      <h1><a href="/">Raagtime - From Dawn till Dusk</a></h1>
      <%= render partial: "layouts/flash_messages" %>
      <%= image_tag "swirl.png", class: "swirl" %>
      <div id="content">
        <%= yield %>
      </div>
    </div>
  </body>
  <%= javascript_include_tag "application" %>
  <%= yield :footer_script_includes %>
</html>

app/views/ragas/_form.html.haml
- semantic_form_for @raga do |form|
  - form.inputs do
    = form.input :title
    = form.input :description, :required => false
    = form.input :ascending_scale
    = form.input :descending_scale
    = form.input :pakad, :required => false
    = form.input :drone, :required => false
    = form.input :time, :as => :select, :collection => Raga.time_options.to_a, :required => false
    = form.input :chakra, :as => :select, :collection => Raga.chakra_options.to_a, :required => false
    = form.input :spotify_playlist_url, :required => false
  - form.buttons do
    = form.commit_button

app/views/ragas/_raga.html.erb
<% cache(raga) do %>
  <tr class="<%= cycle("even", "odd") %>" data-time="<%= raga.time %>" data-thaat="<%= raga.thaat %>">
    <td class="title">
      <%= link_to raga.title, raga %>
    </td>
    <td class="time">
      <%= link_to raga.pretty_time, ragas_path(filter: {time: raga.time}) if raga.time.present? %>
    </td>
    <td class="chakra" data-sort-value="<%= raga.chakra.present? ? raga.chakra.split("_").last : "zzz" %>">
      <% if raga.chakra.present? %>
        <%= image_tag "chakra-icon-#{raga.chakra.split("_").last}.png", alt: raga.chakra, title: raga.chakra.titleize %>
      <% end %>
    </td>
    <td class="thaat">
      <%= link_to raga.thaat, ragas_path(filter: {thaat: raga.thaat}) if raga.thaat.present? %>
    </td>
    <td class="spotify">
      <% if raga.spotify_playlist_url %>
        <%= link_to image_tag("spotify_icon_small.png", alt: "Spotify"), raga.spotify_playlist_url, title: "Spotify playlist" %>
      <% end %>
      <% if raga.clips_count > 0 %>
        <%= link_to image_tag("youtube.png", class: "youtube-icon"), raga_path(raga, anchor: "songs"), title: "YouTube clips" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/ragas/_suggestion.html.erb
<% has_time_offset = session[:time_zone_offset].present? %>

<div id="raga-suggestion" <%= "data-needs-load" unless has_time_offset %>>
  <p class="suggestion">
    <% if has_time_offset %>
      <%= "It's #{pretty_clock} o clock." %>
      <%= raga_suggestion %>
      <%= "Or #{link_to("filter all ragas", ragas_path(filter: {time: time_to_prahar}), id: "suggestion-time-filter-link", data: {time: time_to_prahar})} suitable for this time.".html_safe %>
    <% end %>
  </p>
</div>

app/views/ragas/edit.html.haml
- title "Editing #{@raga}"

= render :partial => "form"

= link_to "Show", @raga
= link_to "Back", ragas_path

app/views/ragas/index.html.erb
<% title "Listing Ragas" %>

<%= render partial: "suggestion" %>

<% cache "all_ragas#{params[:order]}#{params[:filter]}", skip_digest: true do %>

<%= image_tag "swirl.png", class: "swirl" %>

<h2>Rāgas</h2>

<div class="filter">
  <p>
    Filtering on
    <span class="filter-name">
      time 09-12
    </span>
    <%= link_to("remove filter", root_path, id: "remove-filter-link") %>.
  </p>
</div>

<table id="ragas">
  <thead>
    <tr>
      <th class="title" data-sort="string">
        <div class="left">Title</div>
        <%= image_tag "sort_arrow.gif" %>
      </th>
      <th class="time" data-sort="string">
        <div class="left">Time</div>
        <%= image_tag "sort_arrow.gif" %>
      </th>
      <th class="chakra" data-sort="string">
        <div class="left">Chakra</div>
        <%= image_tag "sort_arrow.gif" %>
      </th>
      <th class="thaat" data-sort="string">
        <div class="left">Thaat</div>
        <%= image_tag "sort_arrow.gif" %>
      </th>
      <th class="spotify"></th>
    </tr>
  </thead>
  <tbody>
    <%= render ragas %>
  </tbody>
</table>

<% end %>

<% content_for :footer_script_includes do %>
  <%= javascript_include_tag "ragas" %>
<% end %>

app/views/ragas/new.html.haml
- title "New Raga"

= render :partial => "form"

= link_to "Back", ragas_path

app/views/ragas/show.html.erb
<% cache @raga do %>
<% title "Raag #{@raga.title}" %>

<h2><%= @page_title %></h2>

<% if @raga.description %>
  <%= simple_format @raga.description %>
<% end %>

<%= attribute_for @raga, :time, :value => @raga.pretty_time if @raga.time.present? %>

<% if @raga.chakra.present? %>
  <%= attribute_for @raga, :chakra, :value => @raga.pretty_chakra %>
  <%= chakra_image @raga.chakra %>
<% end %>

<%= attribute_for @raga, :ascending_scale %>
<%= attribute_for @raga, :descending_scale %>
<%= attribute_for @raga, :pakad if @raga.pakad.present? %>
<%= attribute_for @raga, :drone if @raga.drone.present? %>

<% if @raga.spotify_playlist_url %>
  <iframe class="spotify-playlist" height="480" src="https://embed.spotify.com/?uri=<%= @raga.spotify_playlist_url %>" width="332"></iframe>
<% end %>

<a name="songs"><h2>Songs and Performances</h2></a>

<% @raga.clips.each do |clip| %>
  <% next if clip.new_record? %>

  <div class="clip-wrapper">
    <%= clip.embed_code.html_safe %>
  </div>
<% end %>

<div class="clear"></div>
<% end %>

<%= semantic_form_for @clip do |form| %>
  <%= form.inputs class: "left" do %>
    <%= form.input :url, label: "YouTube URL", required: false, input_html: { class: "" } %>
    <%= form.input :raga_id, as: :hidden %>
  <% end %>
  <%= form.actions class: "left" do %>
    <%= form.action :submit, as: :button, label: "Add Clip" %>
  <% end %>
<% end %>

<div class="clear"></div>